# Generated by configure script
# Electron Bar Graph Makefile

# Configuration
PREFIX = /opt/custom
BINDIR = /opt/custom/bin
DATADIR = /opt/custom/share/electron-bar-graph
EMACS_PREFIX = /usr/local
EMACS_INTEGRATION = yes
EMACS_BUILD = no
DEBUG = no
VERBOSE = no
BUILD_TYPE = release
NODE_VERSION = 18
BUN_VERSION = latest

# Directories
SRCDIR = electron-bar-graph
BUILDDIR = build
DISTDIR = dist

# Files
MAIN_JS = $(SRCDIR)/main.js
RENDERER_JS = $(SRCDIR)/renderer.js
INDEX_HTML = $(SRCDIR)/index.html
STYLE_CSS = $(SRCDIR)/style.css
BAR_GRAPH_EL = $(SRCDIR)/bar-graph.el
PACKAGE_JSON = $(SRCDIR)/package.json
CONFIG_H = config.h

# Default target
all: build

# Build targets
build: $(CONFIG_H)
	@echo "Building Electron Bar Graph..."
	@mkdir -p $(BUILDDIR)
	@cp -r $(SRCDIR)/* $(BUILDDIR)/
	@cp $(CONFIG_H) $(BUILDDIR)/
	@cd $(BUILDDIR) && bun install
	@echo "Build complete!"

# Install targets
install: build
	@echo "Installing Electron Bar Graph..."
	@mkdir -p $(BINDIR)
	@mkdir -p $(DATADIR)
	@cp -r $(BUILDDIR)/* $(DATADIR)/
	@echo "#!/bin/bash" > $(BINDIR)/electron-bar-graph
	@echo "cd $(DATADIR) && electron . \"$\"" >> $(BINDIR)/electron-bar-graph
	@chmod +x $(BINDIR)/electron-bar-graph
	@echo "Installation complete!"
	@echo "Note: You may need to run 'make install' as root for system-wide installation"

# Clean targets
clean:
	@echo "Cleaning build files..."
	@rm -rf $(BUILDDIR)
	@rm -rf $(DISTDIR)
	@rm -f $(CONFIG_H)
	@echo "Clean complete!"

# Distclean target
distclean: clean
	@echo "Cleaning all generated files..."
	@rm -f Makefile
	@rm -rf emacs-build
	@echo "Distclean complete!"

# Test targets
test: build
	@echo "Running comprehensive test suite..."
	@cd $(BUILDDIR) && npm test
	@echo "Test suite completed!"

# Test targets with coverage
test-coverage: build
	@echo "Running tests with coverage..."
	@cd $(BUILDDIR) && npm run test:coverage
	@echo "Coverage report generated!"

# Test targets in watch mode
test-watch: build
	@echo "Running tests in watch mode..."
	@cd $(BUILDDIR) && npm run test:watch

# Test specific test files
test-unit: build
	@echo "Running unit tests..."
	@cd $(BUILDDIR) && npx jest tests/main.test.js tests/renderer.test.js tests/utils.test.js

test-integration: build
	@echo "Running integration tests..."
	@cd $(BUILDDIR) && npx jest tests/integration.test.js tests/config.test.js

test-e2e: build
	@echo "Running end-to-end tests..."
	@cd $(BUILDDIR) && npx jest tests/e2e.test.js

test-performance: build
	@echo "Running performance tests..."
	@cd $(BUILDDIR) && npx jest tests/performance.test.js

test-ui: build
	@echo "Running UI tests..."
	@cd $(BUILDDIR) && npx jest tests/ui.test.js

test-emacs: build
	@echo "Running Emacs integration tests..."
	@cd $(BUILDDIR) && npx jest tests/emacs.test.js

# Development targets
dev: build
	@echo "Starting development server..."
	@cd $(BUILDDIR) && bun run dev

# Package targets
package: build
	@echo "Creating package..."
	@mkdir -p $(DISTDIR)
	@tar -czf $(DISTDIR)/electron-bar-graph-$(BUILD_TYPE).tar.gz -C $(BUILDDIR) .
	@echo "Package created: $(DISTDIR)/electron-bar-graph-$(BUILD_TYPE).tar.gz"

# Help target
help:
	@echo "Available targets:"
	@echo "  build          - Build the application"
	@echo "  install        - Install the application"
	@echo "  clean          - Clean build files"
	@echo "  distclean      - Clean all generated files"
	@echo "  test           - Run comprehensive test suite"
	@echo "  test-coverage  - Run tests with coverage report"
	@echo "  test-watch     - Run tests in watch mode"
	@echo "  test-unit      - Run unit tests only"
	@echo "  test-integration - Run integration tests only"
	@echo "  test-e2e       - Run end-to-end tests only"
	@echo "  test-performance - Run performance tests only"
	@echo "  test-ui        - Run UI tests only"
	@echo "  test-emacs     - Run Emacs integration tests only"
	@echo "  dev            - Start development server"
	@echo "  package        - Create distribution package"
	@echo "  help           - Show this help"

.PHONY: all build install clean distclean test test-coverage test-watch test-unit test-integration test-e2e test-performance test-ui test-emacs dev package help
